### ISSUE TITLE
采用calico网络方案，peer pod 启动失败

### ISSUE THREAD

**Issue by ZhengRongTan** [hainingzhang/articles#6]
如题， peer pod启动不起来，查看日志报以下错误：

2018-04-19 06:55:03.293 UTC [nodeCmd] createChaincodeServer -&gt; WARN 042 peer.chaincodeListenAddress is not set, using peer1.org1:7052
2018-04-19 06:55:03.296 UTC [nodeCmd] createChaincodeServer -&gt; ERRO 043 Error creating GRPC server: listen tcp 10.254.45.199:7052: bind: cannot assign requested address
2018-04-19 06:55:03.296 UTC [nodeCmd] serve -&gt; CRIT 044 Failed to create chaincode server: listen tcp 10.254.45.199:7052: bind: cannot assign requested address
panic: Failed to create chaincode server: listen tcp 10.254.45.199:7052: bind: cannot assign requested address
goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/github.com/op/go-logging.(*Logger).Panicf(0xc42024c1b0, 0xf0a90e, 0x25, 0xc4203b1ec0, 0x1, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/op/go-logging/logger.go:194 +0x134
github.com/hyperledger/fabric/peer/node.serve(0x16c5708, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:195 +0x8a9
github.com/hyperledger/fabric/peer/node.glob..func1(0x164ce80, 0x16c5708, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/peer/node/start.go:87 +0x3f
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute(0x164ce80, 0x16c5708, 0x0, 0x0, 0x164ce80, 0x16c5708)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x164d4e0, 0x11, 0xc420213130, 0x5)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute(0x164d4e0, 0x1b, 0xc42001a035)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:112 +0x5e1

**Comment by ZhengRongTan** [comment]
参考
https://github.com/MCLDG/fabric-on-kubernetes
