### ISSUE TITLE
使用fabric on helm时orderer0不能正常启动

### ISSUE THREAD

**Issue by okzhchy** [hainingzhang/articles#8]
按照fabric_helm文档步骤，使用helm install启动后，其他部分正常，但orderer0不能正常启动。
查看orderer0的log发现：
2018-08-28 01:23:03.679 UTC [orderer/main] createSubDir -> DEBU 021 Found chains sub-dir and using it
panic: Unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory
去nfs里查看genesis.block确实是个目录，请教这是什么问题？如何解决？

该pod的完整log如下：
[root@k8s11-master fabric-chart]# kubectl logs orderer0-748f846979-xt966 -n orderer-cluster       
2018-08-28 01:23:03.571 UTC [orderer/main] main -> INFO 001 Starting orderer:
 Version: 1.0.5
 Go version: go1.7.5
 OS/Arch: linux/amd64
2018-08-28 01:23:03.581 UTC [bccsp_sw] openKeyStore -> DEBU 002 KeyStore opened at [/var/hyperledger/orderer/msp/keystore]...done
2018-08-28 01:23:03.581 UTC [bccsp] initBCCSP -> DEBU 003 Initialize BCCSP [SW]
2018-08-28 01:23:03.581 UTC [msp] getPemMaterialFromDir -> DEBU 004 Reading directory /var/hyperledger/orderer/msp/signcerts
2018-08-28 01:23:03.582 UTC [msp] getPemMaterialFromDir -> DEBU 005 Inspecting file /var/hyperledger/orderer/msp/signcerts/orderer0.orderer.com-cert.pem
2018-08-28 01:23:03.583 UTC [msp] getPemMaterialFromDir -> DEBU 006 Reading directory /var/hyperledger/orderer/msp/cacerts
2018-08-28 01:23:03.584 UTC [msp] getPemMaterialFromDir -> DEBU 007 Inspecting file /var/hyperledger/orderer/msp/cacerts/ca.orderer.com-cert.pem
2018-08-28 01:23:03.584 UTC [msp] getPemMaterialFromDir -> DEBU 008 Reading directory /var/hyperledger/orderer/msp/admincerts
2018-08-28 01:23:03.585 UTC [msp] getPemMaterialFromDir -> DEBU 009 Inspecting file /var/hyperledger/orderer/msp/admincerts/Admin@orderer.com-cert.pem
2018-08-28 01:23:03.585 UTC [msp] getPemMaterialFromDir -> DEBU 00a Reading directory /var/hyperledger/orderer/msp/intermediatecerts
2018-08-28 01:23:03.585 UTC [msp] getMspConfig -> DEBU 00b Intermediate certs folder not found at [/var/hyperledger/orderer/msp/intermediatecerts]. Skipping. [stat /var/hyperledger/orderer/msp/intermediatecerts: no such file or directory]
2018-08-28 01:23:03.585 UTC [msp] getPemMaterialFromDir -> DEBU 00c Reading directory /var/hyperledger/orderer/msp/tlscacerts
2018-08-28 01:23:03.586 UTC [msp] getPemMaterialFromDir -> DEBU 00d Inspecting file /var/hyperledger/orderer/msp/tlscacerts/tlsca.orderer.com-cert.pem
2018-08-28 01:23:03.586 UTC [msp] getPemMaterialFromDir -> DEBU 00e Reading directory /var/hyperledger/orderer/msp/tlsintermediatecerts
2018-08-28 01:23:03.586 UTC [msp] getMspConfig -> DEBU 00f TLS intermediate certs folder not found at [/var/hyperledger/orderer/msp/tlsintermediatecerts]. Skipping. [stat /var/hyperledger/orderer/msp/tlsintermediatecerts: no such file or directory]
2018-08-28 01:23:03.586 UTC [msp] getPemMaterialFromDir -> DEBU 010 Reading directory /var/hyperledger/orderer/msp/crls
2018-08-28 01:23:03.586 UTC [msp] getMspConfig -> DEBU 011 crls folder not found at [/var/hyperledger/orderer/msp/crls]. Skipping. [stat /var/hyperledger/orderer/msp/crls: no such file or directory]
2018-08-28 01:23:03.586 UTC [msp] getMspConfig -> DEBU 012 MSP configuration file not found at [/var/hyperledger/orderer/msp/config.yaml]: [stat /var/hyperledger/orderer/msp/config.yaml: no such file or directory]
2018-08-28 01:23:03.587 UTC [msp] NewBccspMsp -> DEBU 013 Creating BCCSP-based MSP instance
2018-08-28 01:23:03.587 UTC [msp] GetLocalMSP -> DEBU 014 Created new local MSP
2018-08-28 01:23:03.587 UTC [msp] Setup -> DEBU 015 Setting up MSP instance OrdererMSP
2018-08-28 01:23:03.587 UTC [msp/identity] newIdentity -> DEBU 016 Creating identity instance for ID -----BEGIN CERTIFICATE-----
MIICMDCCAdagAwIBAgIRAPkAcwPNlUVAbs9nSHYHcscwCgYIKoZIzj0EAwIwaTEL
MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
cmFuY2lzY28xFDASBgNVBAoTC29yZGVyZXIuY29tMRcwFQYDVQQDEw5jYS5vcmRl
cmVyLmNvbTAeFw0xODA4MjgwMTE0MjBaFw0yODA4MjUwMTE0MjBaMGkxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
c2NvMRQwEgYDVQQKEwtvcmRlcmVyLmNvbTEXMBUGA1UEAxMOY2Eub3JkZXJlci5j
b20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAR8IUC7GS+BegaWBKmXfYu/pLEn
pLlOeuIc3dms8qJqi4KVJi+cwRkjEsJz1OzXGUT1hbeq+Qv4evOYx0Rdm+dOo18w
XTAOBgNVHQ8BAf8EBAMCAaYwDwYDVR0lBAgwBgYEVR0lADAPBgNVHRMBAf8EBTAD
AQH/MCkGA1UdDgQiBCDWFftVLigtQJ0mJFpzRDD2zhUjU9yVT70bouTgImxhyjAK
BggqhkjOPQQDAgNIADBFAiEAlWvrzGYRV1ykSG2JILuSyfXyPyxg3LDm9dZdtVMc
s0oCIG9PCIycWqRHoj0DPTr3TQq5/SoG+/VQm2RxChAP4A31
-----END CERTIFICATE-----
2018-08-28 01:23:03.647 UTC [msp/identity] newIdentity -> DEBU 017 Creating identity instance for ID -----BEGIN CERTIFICATE-----
MIICCjCCAbCgAwIBAgIQcoP1vMtacbJL2dShXNT0gTAKBggqhkjOPQQDAjBpMQsw
CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
YW5jaXNjbzEUMBIGA1UEChMLb3JkZXJlci5jb20xFzAVBgNVBAMTDmNhLm9yZGVy
ZXIuY29tMB4XDTE4MDgyODAxMTQyMFoXDTI4MDgyNTAxMTQyMFowVjELMAkGA1UE
BhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lz
Y28xGjAYBgNVBAMMEUFkbWluQG9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEc/gCUkDZRzH+qllLeA5yBI1/6I4rVFhblpg180rIbQF4QoQc4cWA
0modWeCPeZGxLfVKr2WzsFogwPzLRjryTqNNMEswDgYDVR0PAQH/BAQDAgeAMAwG
A1UdEwEB/wQCMAAwKwYDVR0jBCQwIoAg1hX7VS4oLUCdJiRac0Qw9s4VI1PclU+9
G6Lk4CJsYcowCgYIKoZIzj0EAwIDSAAwRQIhAPYEsfDYQpnzG2q1ZUDoOh16l/Sx
5nLo1aGidwjZrtuLAiAktAZSRo+DI/1XECWo/rK/IMy2XQg2k8aBMGzRvMJ7EA==
-----END CERTIFICATE-----
2018-08-28 01:23:03.647 UTC [msp/identity] newIdentity -> DEBU 018 Creating identity instance for ID -----BEGIN CERTIFICATE-----
MIICCjCCAbCgAwIBAgIQcoP1vMtacbJL2dShXNT0gTAKBggqhkjOPQQDAjBpMQsw
CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
YW5jaXNjbzEUMBIGA1UEChMLb3JkZXJlci5jb20xFzAVBgNVBAMTDmNhLm9yZGVy
ZXIuY29tMB4XDTE4MDgyODAxMTQyMFoXDTI4MDgyNTAxMTQyMFowVjELMAkGA1UE
BhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lz
Y28xGjAYBgNVBAMMEUFkbWluQG9yZGVyZXIuY29tMFkwEwYHKoZIzj0CAQYIKoZI
zj0DAQcDQgAEc/gCUkDZRzH+qllLeA5yBI1/6I4rVFhblpg180rIbQF4QoQc4cWA
0modWeCPeZGxLfVKr2WzsFogwPzLRjryTqNNMEswDgYDVR0PAQH/BAQDAgeAMAwG
A1UdEwEB/wQCMAAwKwYDVR0jBCQwIoAg1hX7VS4oLUCdJiRac0Qw9s4VI1PclU+9
G6Lk4CJsYcowCgYIKoZIzj0EAwIDSAAwRQIhAPYEsfDYQpnzG2q1ZUDoOh16l/Sx
5nLo1aGidwjZrtuLAiAktAZSRo+DI/1XECWo/rK/IMy2XQg2k8aBMGzRvMJ7EA==
-----END CERTIFICATE-----
2018-08-28 01:23:03.649 UTC [msp/identity] newIdentity -> DEBU 019 Creating identity instance for ID -----BEGIN CERTIFICATE-----
MIICDjCCAbSgAwIBAgIRAJNwT9y5TwKS1JfY/R+QkPwwCgYIKoZIzj0EAwIwaTEL
MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
cmFuY2lzY28xFDASBgNVBAoTC29yZGVyZXIuY29tMRcwFQYDVQQDEw5jYS5vcmRl
cmVyLmNvbTAeFw0xODA4MjgwMTE0MjBaFw0yODA4MjUwMTE0MjBaMFkxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
c2NvMR0wGwYDVQQDExRvcmRlcmVyMC5vcmRlcmVyLmNvbTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABMzEThK7QeFl6jd3kgDe9VhcT+ALE59fqQWhnxfm2eDjQpU7
Okj4pl1WFGbiQ8tU5tvrV9J6JaGMubKbcRE/lb+jTTBLMA4GA1UdDwEB/wQEAwIH
gDAMBgNVHRMBAf8EAjAAMCsGA1UdIwQkMCKAINYV+1UuKC1AnSYkWnNEMPbOFSNT
3JVPvRui5OAibGHKMAoGCCqGSM49BAMCA0gAMEUCIQDwXWbyW+e+T9a12UOSKqUa
wDTelPFcX0vZrCmi3jhi1QIgQa70RtOAqkEsi94SYFzjahB5fbsiY8hN+S9uK8xp
Wb4=
-----END CERTIFICATE-----
2018-08-28 01:23:03.650 UTC [bccsp_sw] loadPrivateKey -> DEBU 01a Loading private key [069fd4d23082d331e6ec12981f73eaa7a6cb9f89692da07b09be6003787bd351] at [/var/hyperledger/orderer/msp/keystore/069fd4d23082d331e6ec12981f73eaa7a6cb9f89692da07b09be6003787bd351_sk]...
2018-08-28 01:23:03.650 UTC [msp/identity] newIdentity -> DEBU 01b Creating identity instance for ID -----BEGIN CERTIFICATE-----
MIICDjCCAbSgAwIBAgIRAJNwT9y5TwKS1JfY/R+QkPwwCgYIKoZIzj0EAwIwaTEL
MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
cmFuY2lzY28xFDASBgNVBAoTC29yZGVyZXIuY29tMRcwFQYDVQQDEw5jYS5vcmRl
cmVyLmNvbTAeFw0xODA4MjgwMTE0MjBaFw0yODA4MjUwMTE0MjBaMFkxCzAJBgNV
BAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNp
c2NvMR0wGwYDVQQDExRvcmRlcmVyMC5vcmRlcmVyLmNvbTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABMzEThK7QeFl6jd3kgDe9VhcT+ALE59fqQWhnxfm2eDjQpU7
Okj4pl1WFGbiQ8tU5tvrV9J6JaGMubKbcRE/lb+jTTBLMA4GA1UdDwEB/wQEAwIH
gDAMBgNVHRMBAf8EAjAAMCsGA1UdIwQkMCKAINYV+1UuKC1AnSYkWnNEMPbOFSNT
3JVPvRui5OAibGHKMAoGCCqGSM49BAMCA0gAMEUCIQDwXWbyW+e+T9a12UOSKqUa
wDTelPFcX0vZrCmi3jhi1QIgQa70RtOAqkEsi94SYFzjahB5fbsiY8hN+S9uK8xp
Wb4=
-----END CERTIFICATE-----
2018-08-28 01:23:03.652 UTC [msp] Validate -> DEBU 01c MSP OrdererMSP validating identity
2018-08-28 01:23:03.652 UTC [orderer/main] createLedgerFactory -> DEBU 01d Ledger dir: /var/hyperledger/production/orderer
2018-08-28 01:23:03.652 UTC [kvledger.util] CreateDirIfMissing -> DEBU 01e CreateDirIfMissing [/var/hyperledger/production/orderer/index/]
2018-08-28 01:23:03.653 UTC [kvledger.util] logDirStatus -> DEBU 01f Before creating dir - [/var/hyperledger/production/orderer/index/] exists
2018-08-28 01:23:03.653 UTC [kvledger.util] logDirStatus -> DEBU 020 After creating dir - [/var/hyperledger/production/orderer/index/] exists
2018-08-28 01:23:03.679 UTC [orderer/main] createSubDir -> DEBU 021 Found chains sub-dir and using it
panic: Unable to bootstrap orderer. Error reading genesis block file: read /var/hyperledger/orderer/orderer.genesis.block: is a directory

goroutine 1 [running]:
panic(0xb72100, 0xc4202f0640)
        /opt/go/src/runtime/panic.go:500 +0x1a1
github.com/hyperledger/fabric/orderer/common/bootstrap/file.(*fileBootstrapper).GenesisBlock(0xc4202f0630, 0xc4202f0630)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/common/bootstrap/file/bootstrap.go:44 +0x233
main.initializeBootstrapChannel(0xc42021ad80, 0x1246880, 0xc4203a6220)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:162 +0x759
main.initializeMultiChainManager(0xc42021ad80, 0x1243480, 0x128b4a8, 0xc420220e10, 0x1)
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:211 +0xa0
main.main()
        /opt/gopath/src/github.com/hyperledger/fabric/orderer/main.go:75 +0x392

**Comment by zhaopf2017** [comment]
docker外应该存在这个文件，如果不存在，就会建立一个目录。
 

 

 
 
 
------------------ Original ------------------

**Comment by okzhchy** [comment]
@zhaopf2017 是需要手动生成吗？我使用cryptogen生成的crypto-config里面并没有这个文件。

**Comment by jiahaoc1993** [comment]
@okzhchy Hi，genesis.blcok 需要通过configtxgen工具生成，生成之后请手动把它移动到 crypto-config/ordererOrganizations/example.com下，
